export const TodoActionTypes = {
  SET_SHOW_ADDTODO: "SET_SHOW_ADDTODO",
  SET_TODO: "SET_TODO",
  CLEAR_TODO: "CLEAR_TODO",
  SET_TODO_WITHDATE: "SET_TODO_WITHDATE",
  SET_TODO_WITHTODAY: "SET_TODO_WITHTODAY",
  SET_TODO_WITHDUE: "SET_TODO_WITHDUE",
  SET_TODO_WITHPROJECT: "SET_TODO_WITHPROJECT",
};
